export enum HttpCode {
    ok = 200,
    created = 201,
    badRequest = 400,
    unauthorized = 401,
    forbidden = 403,
    notFound = 404,
    conflict = 409,
    validationError = 422,
    internalServerError = 500,
    notImplemented = 501,
    serviceUnavailable = 503,
    gatewayTimeout = 504,
    tooManyRequests = 429,
    methodNotAllowed = 405,
    notAcceptable = 406,
    preconditionFailed = 412,
    unsupportedMediaType = 415,
    badGateway = 502,
    expectationFailed = 417,
    misdirectedRequest = 421,
    locked = 423,
    failedDependency = 424,
};

export enum ErrorType {
    ApplicationError = "ApplicationError",
    BadRequest = "BadRequestError",
    Unauthorized = "UnauthorizedError",
    Forbidden = "ForbiddenError",
    NotFound = "NotFoundError",
    Conflict = "ConflictError",
    InternalServerError = "InternalServerError",
    ValidationError = "ValidationError",
    NotImplemented = "NotImplementedError",
    ServiceUnavailable = "ServiceUnavailableError",
    GatewayTimeout = "GatewayTimeoutError",
    TooManyRequests = "TooManyRequestsError",
    UnprocessableEntity = "UnprocessableEntityError",
    MethodNotAllowed = "MethodNotAllowedError",
    NotAcceptable = "NotAcceptableError",
    PreconditionFailed = "PreconditionFailedError",
    UnsupportedMediaType = "UnsupportedMediaTypeError",
    BadGateway = "BadGatewayError",
    ExpectationFailed = "ExpectationFailedError",
    MisdirectedRequest = "MisdirectedRequestError",
    Locked = "LockedError",
    FailedDependency = "FailedDependencyError",
};

export enum NotificationType{
    info = 'info',
    success = 'success',
    warning = 'warning',
    error = 'error',
    critical = 'critical'
};